### ISSUE TITLE
Can't build on Windows: Conflicting Types

### ISSUE THREAD

**Issue by aricus** [ninovanhooff/wheelsprung#1]
Set up nim/nimble etc on Windows and when I try to compile this with nimble simulator I get this error no matter what I try

\playdate\api.nim:55:28: error: conflicting types for 'NimMain'; have 'void(void)'

**Comment by ninovanhooff** [comment]
That error is in the Playdate module.

Try to reproduce the issue by compiling the example in https://github.com/samdze/playdate-nim using vscode to isolate the issue. Use vscode. If the issue can be reproduced, you can open an issue there, and close this one

**Comment by ninovanhooff** [comment]
Actually, there is another problem: libchipmunk is not compiled for windows yet. See the lib folder

**Comment by ninovanhooff** [comment]
I mafe an attempt to find the windows lib, but couldn't find it. 

I thought I found it here, https://packages.msys2.org/package/mingw-w64-x86_64-chipmunk?repo=mingw64 
But using that libchipmunk.a file in there doesn't work

**Comment by ninovanhooff** [comment]
Update: windows support is now added. So when you get that initial issue sorted, you should be good to go.

**Comment by ninovanhooff** [comment]
Closing.
Feel free to re-open this issue if the error if you can build the nim example project but not this one
